CREATE TABLE Assisted (
  CustID INT NOT NULL,
  EmpID INT NOT NULL,
  PRIMARY KEY (CustID, EmpID),
  FOREIGN KEY(CustID) REFERENCES Customer(CustID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  FOREIGN KEY(EmpID) REFERENCES Employee(EmpID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);