CREATE TABLE Inventory (
  InventoryName VARCHAR(32) PRIMARY KEY,
  BookID INT UNIQUE,
  ManID INT,
  InvQuantity INT NOT NULL,
  RestockThres INT NOT NULL,
  FOREIGN KEY (BookID) REFERENCES Book(BookID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  FOREIGN KEY (ManID) REFERENCES Employee(EmpID)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);
