CREATE TABLE Orders (
  OrderID INT PRIMARY KEY,
  CustID INT NOT NULL,
  CashID INT,
  PaymentID INT,
  ShipStreet VARCHAR(64) NOT NULL,
  ShipCity VARCHAR(32) NOT NULL,
  ShipState CHAR(2) NOT NULL,
  ShipZip INT NOT NULL,
  PaymentStatus BOOLEAN NOT NULL,
  OrderDate DATE NOT NULL,
  ShipDate DATE,
  FOREIGN KEY(CustID) REFERENCES Customer(CustID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  FOREIGN KEY(CashID) REFERENCES Employee(EmpID)
    ON UPDATE CASCADE
    ON DELETE SET NULL,
  FOREIGN KEY(PaymentID) REFERENCES Payment(PaymentID)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);
